### ISSUE TITLE
lineup.json error

### ISSUE THREAD

**Issue by CollabSensei** [chkuendig/tvhProxy#1]
When fetching the lineup.json, it is throwing some python errors.
ERROR:tvhProxy:Exception on /lineup.json [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.7/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "tvhProxy.py", line 73, in lineup
    for c in _get_channels():
TypeError: 'NoneType' object is not iterable

I am running Tvheadend 4.3

**Comment by chkuendig** [comment]
Is it possible you have enabled digest auth in the tvheadend settings? This script currently only supports HTTP basic auth.

**Comment by chkuendig** [comment]
This should now be fixed with #2
