### ISSUE TITLE
JSONDecodeError

### ISSUE THREAD

**Issue by 0xc0re** [chkuendig/tvhProxy#4]
I am receiving this error when Plex hits /lineup.json

`ERROR:root:An error occured: %sJSONDecodeError('Expecting value: line 1 column 1 (char 0)',)
ERROR:tvhProxy:Exception on /lineup.json [GET]
Traceback (most recent call last):
  File "/home/c0re/src/tvhProxy/.venv/lib/python3.6/site-packages/flask/app.py", line 2447, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/c0re/src/tvhProxy/.venv/lib/python3.6/site-packages/flask/app.py", line 1952, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/c0re/src/tvhProxy/.venv/lib/python3.6/site-packages/flask/app.py", line 1821, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/c0re/src/tvhProxy/.venv/lib/python3.6/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/c0re/src/tvhProxy/.venv/lib/python3.6/site-packages/flask/app.py", line 1950, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/c0re/src/tvhProxy/.venv/lib/python3.6/site-packages/flask/app.py", line 1936, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "tvhProxy.py", line 82, in lineup
    for c in _get_channels():
TypeError: 'NoneType' object is not iterable
INFO:root:192.168.20.18 - - [2020-10-21 12:44:25] "GET /lineup.json HTTP/1.0" 500 445 0.015836
`

Any ideas?

**Comment by 0xc0re** [comment]
It was an issue with tvheadend. My aplogies.
